@User_Service_HostAddress = http://localhost:5002

GET {{User_Service_HostAddress}}/weatherforecast/
Accept: application/json

###


    // "MySQLConnection": "Server=DB-User;Port=3306;Database=userdb;User=root;Password=root;"
