version: '3.8'

services:
  # PostgreSQL Database service
  postgres:
    image: postgres:15
    container_name: DB-User
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: spotify
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # User Service backend
  user-service:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: soulaimane00/service-user:2.0.0  # Use the correct image tag
    container_name: Service-User
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=123456;Database=spotify
    depends_on:
      - postgres
    command: ["sh", "-c", "until pg_isready -h postgres -p 5432; do sleep 2; done; dotnet User.Service.dll"]
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: soulaimane00/frontend:2.0.0  # Use the correct image tag
    container_name: Frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
    networks:
      - app-network

volumes:
  pgdata:  # For PostgreSQL data persistence

networks:
  app-network:
    driver: bridge