version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: ${DOCKER_IMAGE_FRONTEND}:1.0.0
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Backend Service
  user-service:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: ${DOCKER_IMAGE_BACKEND}:1.0.0
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=123456;Database=spotify
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
