version: '3.8'

services:
  postgres:
    image: ${{ secrets.DOCKER_USERNAME }}/repo-name-postgres:latest  # Docker Hub tag
    container_name: DB-User
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: spotify
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: ${{ secrets.DOCKER_USERNAME }}/repo-name-user-service:latest  # Docker Hub tag
    container_name: Service-User
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=123456;Database=spotify
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: ${{ secrets.DOCKER_USERNAME }}/repo-name-frontend:latest  # Docker Hub tag
    container_name: Frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
    networks:
      - app-network

volumes:
  pgdata:  # For PostgreSQL data persistence

networks:
  app-network:
    driver: bridge
