version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: DB-User
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userDb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - spotify

  user-service:
    build:
      context: . # Point to the source code directory
      dockerfile: ./docker/backend/user/Dockerfile # Relative path to the Dockerfile
    container_name: Service-User
    ports:
      - "8091:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=mysql;Port=3306;Database=userDb;Username=myuser;Password=mypassword
    depends_on:
      - mysql
    networks:
      - spotify

networks:
  spotify:
    driver: bridge

volumes:
  mysql-db:
