import requests
import json

# API endpoint
url = "http://localhost:5002/api/albums"  # Replace with your actual API endpoint

# Load albums from JSON file
with open("Albums.json", "r") as file:
    albums = json.load(file)

# Iterate through albums and send POST requests
for album in albums:
    # Remove "id" field since it might be generated by the backend
    album.pop("id", None)
    
    try:
        response = requests.post(url, json=album)
        if response.status_code == 201:  # Created
            print(f"Successfully added album: {album['title']}")
        else:
            print(f"Failed to add album: {album['title']} (Status code: {response.status_code})")
            print("Response:", response.text)
    except Exception as e:
        print(f"Error adding album {album['title']}: {e}")
