name: CI/CD Pipeline

on:
  push:
    branches:
      - dev  # Trigger on push to the 'dev' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (if required)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker images (optional)
      # - name: Build and push Docker images
      #   run: |
      #     docker build -t your-dockerhub-username/user-service:latest -f docker/backend/Dockerfile .
      #     docker build -t your-dockerhub-username/frontend:latest -f docker/frontend/Dockerfile .

      # Step 5: Run Docker Compose to start services
      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yml up --build -d
