name: Docker Publish

on:
  push:
    branches:
      - dev 

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_BACKEND: soulaimane00/service-user
      DOCKER_IMAGE_FRONTEND: soulaimane00/frontend

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Check out the latest code from the repository

      # Install docker-compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub to push images
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push images using docker-compose
      - name: Build and Push with Docker Compose
        run: |
          # Build the images using docker-compose
          docker-compose -f docker-compose-publish.yml build --no-cache

          # Push the backend image to Docker Hub
          docker push $DOCKER_IMAGE_BACKEND:1.0.0

          # Push the frontend image to Docker Hub
          docker push $DOCKER_IMAGE_FRONTEND:1.0.0

      # Optionally: Clean up Docker images after pushing (to avoid large disk usage)
      - name: Clean up Docker images
        run: |
          docker rmi $DOCKER_IMAGE_BACKEND:1.0.0
          docker rmi $DOCKER_IMAGE_FRONTEND:1.0.0
