name: CI Pipeline for Docker Compose

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=2.5.0
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Build and start all services defined in the Docker Compose file
      - name: Build and Start Docker Compose
        run: docker-compose -f docker-compose.yml up --build -d

      # Run tests to verify if containers are running properly
      - name: Run Tests
        run: |
          curl -f http://localhost:8080 || exit 1
          curl -f http://localhost:3000 || exit 1

      # Stop and remove containers after tests
      - name: Stop Docker Compose
        run: docker-compose -f docker-compose.yml down
