name: CI Pipeline for Docker Compose

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for building images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub if needed (optional)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and start all services defined in the Docker Compose file
      - name: Build and Start Docker Compose
        run: docker-compose -f docker-compose.yml up --build -d

      # Run tests to verify if containers are running properly
      - name: Run Tests
        run: |
          # Add your commands here to verify that your containers are running properly
          # Example: curl requests to check if the services are responding
          curl -f http://localhost:8080 || exit 1
          curl -f http://localhost:3000 || exit 1

      # Stop and remove containers after tests
      - name: Stop Docker Compose
        run: docker-compose -f docker-compose.yml down
