name: Docker Publish

on:
  push:
    branches:
      - dev  # Trigger this workflow on push to the 'dev' branch

jobs:
  build-images:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_BACKEND: soulaimane00/service-user
      DOCKER_IMAGE_FRONTEND: soulaimane00/frontend

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Check out the latest code from the repository

      # Install Docker and Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Build images using docker-compose
      - name: Build images with Docker Compose
        run: |
          # Build the images using docker-compose
          docker-compose -f docker-compose-publish.yml build --no-cache

  push-images-to-dockerhub:
    needs: build-images  # Ensures that this job runs only after the build job is completed
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_BACKEND: soulaimane00/service-user
      DOCKER_IMAGE_FRONTEND: soulaimane00/frontend

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub to push images
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the backend image to Docker Hub
      - name: Push Backend Image
        run: |
          docker push $DOCKER_IMAGE_BACKEND:2.0.0

      # Push the frontend image to Docker Hub
      - name: Push Frontend Image
        run: |
          docker push $DOCKER_IMAGE_FRONTEND:2.0.0

      # Optionally: Clean up Docker images after pushing (to avoid large disk usage)
      - name: Clean up Docker images
        run: |
          docker rmi $DOCKER_IMAGE_BACKEND:2.0.0
          docker rmi $DOCKER_IMAGE_FRONTEND:2.0.0
