name: Docker Publish and Deploy

on:
  push:
    branches:
      - dev 

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_BACKEND: soulaimane00/service-user
      DOCKER_IMAGE_FRONTEND: soulaimane00/frontend

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Check out the latest code from the repository

      # Install Docker and Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub to push images
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push images using docker-compose
      - name: Build and Push with Docker Compose
        run: |
          # Build the images using docker-compose
          docker-compose -f docker-compose-publish.yml build --no-cache

          # Push the backend image to Docker Hub
          docker push $DOCKER_IMAGE_BACKEND:1.0.0

          # Push the frontend image to Docker Hub
          docker push $DOCKER_IMAGE_FRONTEND:1.0.0

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull images from Docker Hub
      - name: Pull Backend Image
        run: docker pull $DOCKER_IMAGE_BACKEND:1.0.0

      - name: Pull Frontend Image
        run: docker pull $DOCKER_IMAGE_FRONTEND:1.0.0

      # Run the containers
      - name: Run Backend Container
        run: |
          docker run -d --name user-service -p 8080:8080 $DOCKER_IMAGE_BACKEND:1.0.0

      - name: Run Frontend Container
        run: |
          docker run -d --name frontend -p 3000:3000 $DOCKER_IMAGE_FRONTEND:1.0.0

      # Verify running containers
      - name: List Running Containers
        run: docker ps
